import { XenitionError } from '../core/errors';
import { JSON_TYPE_DECLARATION, MappedType, mapPgType, usesJsonType } from './pg-types';
import { ColumnInfo, IntrospectedSchema, TableInfo } from './types';

export interface EmitOptions {
  /**
   * The command printed in the generated header so whoever reads the file
   * in six months knows how to refresh it. Defaults to the bare CLI name.
   */
  regenerateCommand?: string;
}

/** Default command shown in the generated header. */
export const DEFAULT_REGENERATE_COMMAND = 'npx xenition-codegen --out <this file>';

/**
 * Render an introspected schema as a `.d.ts`.
 *
 * Pure: same schema in, byte-identical text out. That is not a nicety — a
 * generated file is committed, and one that reorders itself or stamps the
 * time of the run produces a diff on every regeneration until people stop
 * reading the diffs, at which point a renamed column slips through
 * unnoticed and the whole exercise has bought nothing.
 */
export function emitDatabaseTypes(
  schema: IntrospectedSchema,
  options: EmitOptions = {},
): string {
  const context = 'emitDatabaseTypes';
  if (!schema || !Array.isArray(schema.tables)) {
    throw new XenitionError('VALIDATION_ERROR', `${context}: pass an introspected schema.`);
  }
  if (schema.tables.length === 0) {
    // Refusing here rather than writing an empty `Database {}` is the
    // point. An empty interface makes `keyof Database` be `never`, so every
    // `from('anything')` call in the app stops compiling with an error that
    // blames the caller instead of the generator — hours lost to a
    // generator that "succeeded".
    throw new XenitionError(
      'QUERY_FAILED',
      `${context}: schema "${schema.schema}" has no tables, so there is nothing to generate. ` +
        'Check the schema name, and that the key used is a service key — ' +
        'raw SQL is rejected for anon keys, and an app with no migrations applied is genuinely empty.',
      { details: { schema: schema.schema } },
    );
  }

  const tables = [...schema.tables].sort((a, b) => compareIdentifiers(a.name, b.name));
  const rendered = tables.map(renderTable);
  const needsJson = rendered.some((table) => table.usesJson);

  const lines: string[] = [];
  lines.push(...header(schema.schema, tables.length, options.regenerateCommand));
  lines.push('');
  if (needsJson) {
    lines.push('/** Anything a `json` / `jsonb` column can hold once parsed. */');
    lines.push(JSON_TYPE_DECLARATION);
    lines.push('');
  }
  lines.push('export interface Database {');
  rendered.forEach((table, index) => {
    if (index > 0) lines.push('');
    lines.push(...table.lines);
  });
  lines.push('}');
  lines.push('');
  lines.push(...helpers());

  return `${lines.join('\n')}\n`;
}

function header(schemaName: string, tableCount: number, regenerate?: string): string[] {
  const command = regenerate ?? DEFAULT_REGENERATE_COMMAND;
  return [
    '/**',
    ' * Generated by @xenition/sdk — DO NOT EDIT BY HAND.',
    ' *',
    ` * Postgres schema "${schemaName}", ${tableCount} ${plural(tableCount, 'table', 'tables')}.`,
    ' * Regenerate with:',
    ` *   ${command}`,
    ' *',
    ' * Each table carries three shapes:',
    ' *   Row     — what SELECT returns. Every column is present; a nullable',
    ' *             column is `| null`.',
    ' *   Insert  — what INSERT accepts. Columns with a default (including',
    ' *             identity columns) and nullable columns are optional,',
    ' *             because the database will supply them.',
    ' *   Update  — a partial write. Every writable column is optional.',
    ' *',
    ' * Columns declared GENERATED ALWAYS appear in Row only: Postgres',
    ' * rejects any statement that writes them, so accepting them in Insert',
    ' * or Update would type-check a query the database refuses.',
    ' *',
    ' * Views appear here alongside tables — information_schema does not',
    ' * distinguish them — so a view\'s Row is exact while its Insert and',
    ' * Update are advisory.',
    ' *',
    ' * Nothing in this file varies between runs: no timestamp, no host, no',
    ' * ordering that depends on the machine that generated it. Regenerating',
    ' * against an unchanged database produces a byte-identical file, so any',
    ' * diff at all means the database actually moved.',
    ' */',
  ];
}

function helpers(): string[] {
  return [
    '/** Every table name in the schema. */',
    'export type TableName = keyof Database;',
    '',
    '/** The row type of one table: `Tables<\'orders\'>`. */',
    "export type Tables<T extends TableName> = Database[T]['Row'];",
    '',
    '/** What INSERT accepts for one table. */',
    "export type TablesInsert<T extends TableName> = Database[T]['Insert'];",
    '',
    '/** What a partial UPDATE accepts for one table. */',
    "export type TablesUpdate<T extends TableName> = Database[T]['Update'];",
  ];
}

interface RenderedTable {
  lines: string[];
  usesJson: boolean;
}

function renderTable(table: TableInfo): RenderedTable {
  const columns = sortColumns(table.columns ?? []);
  const mapped = columns.map((column) => ({ column, type: mapPgType(column) }));
  const writable = mapped.filter((entry) => !entry.column.isGeneratedAlways);

  const lines: string[] = [`  ${quoteIdentifier(table.name)}: {`];
  lines.push(...member('Row', mapped.map((entry) => rowField(entry.column, entry.type))));
  lines.push(...member('Insert', writable.map((entry) => insertField(entry.column, entry.type))));
  lines.push(...member('Update', writable.map((entry) => updateField(entry.column, entry.type))));
  lines.push('  };');

  return { lines, usesJson: mapped.some((entry) => usesJsonType(entry.type)) };
}

/**
 * One of Row / Insert / Update. An empty member becomes
 * `Record<string, never>` rather than `{}`, because `{}` in TypeScript
 * means "any non-nullish value" and would accept every misspelled column
 * anyone ever passed — the opposite of the guarantee this file exists to
 * give.
 */
function member(name: string, fields: string[]): string[] {
  if (fields.length === 0) return [`    ${name}: Record<string, never>;`];
  return [`    ${name}: {`, ...fields.map((field) => `      ${field}`), '    };'];
}

function rowField(column: ColumnInfo, type: MappedType): string {
  const declared = column.isNullable ? `${type.ts} | null` : type.ts;
  return field(column.name, false, declared, type, column.isGeneratedAlways);
}

/**
 * A defaulted column is optional on INSERT; a nullable one is optional and
 * may be written as an explicit null. Both are `?`, and a nullable column
 * additionally keeps `| null` so `{ note: null }` stays legal — omitting a
 * column and clearing it are different intentions and both are valid.
 */
function insertField(column: ColumnInfo, type: MappedType): string {
  const optional = column.hasDefault || column.isNullable;
  const declared = column.isNullable ? `${type.ts} | null` : type.ts;
  return field(column.name, optional, declared, type, false);
}

function updateField(column: ColumnInfo, type: MappedType): string {
  const declared = column.isNullable ? `${type.ts} | null` : type.ts;
  return field(column.name, true, declared, type, false);
}

function field(
  name: string,
  optional: boolean,
  declared: string,
  type: MappedType,
  generatedAlways: boolean,
): string {
  const notes: string[] = [];
  if (type.unmappedPgType) notes.push(`unmapped pg type: ${type.unmappedPgType}`);
  if (generatedAlways) notes.push('GENERATED ALWAYS — not writable');
  const comment = notes.length > 0 ? ` // ${notes.join('; ')}` : '';
  return `${quoteIdentifier(name)}${optional ? '?' : ''}: ${declared};${comment}`;
}

/**
 * Table and column names come from the database, where `order-items`,
 * `2024 totals` and `select` are all legal. Emitting one of those bare
 * produces a `.d.ts` that does not parse, which fails at the point of
 * greatest confusion — a generated file the reader did not write. Reserved
 * words need no quoting: they are valid property names in a type literal.
 */
export function quoteIdentifier(name: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) return name;
  const escaped = name
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `'${escaped}'`;
}

/**
 * Columns follow the table's own ordinal order, which is stable across
 * runs and matches what `\d` shows. A schema assembled by hand may carry no
 * ordinals at all; those fall back to name order rather than to whatever
 * order the array happened to be built in, so the output stays
 * deterministic either way.
 */
function sortColumns(columns: ColumnInfo[]): ColumnInfo[] {
  return [...columns].sort((a, b) => {
    const left = a.ordinalPosition ?? Number.MAX_SAFE_INTEGER;
    const right = b.ordinalPosition ?? Number.MAX_SAFE_INTEGER;
    if (left !== right) return left - right;
    return compareIdentifiers(a.name, b.name);
  });
}

/**
 * Codepoint order, deliberately not `localeCompare`. Locale collation
 * differs between machines and ICU builds, so sorting table names with it
 * would reorder the generated file when a colleague regenerates it —
 * exactly the spurious diff this generator promises not to produce.
 */
export function compareIdentifiers(a: string, b: string): number {
  if (a === b) return 0;
  return a < b ? -1 : 1;
}

function plural(count: number, one: string, many: string): string {
  return count === 1 ? one : many;
}
